#!name=Spotify
#!desc=2026.05.05 部分解锁premium,音质不能设置为超高,登录后再打开脚本,重启app等待脚本生效
# 严禁倒卖等一切非法操作!否则后果自负！
# 功能: 1.去除播放广告 2.歌手/专辑列表正常展示 3.去除随机播放 4.不能离线下载.

[Header Rewrite]
# if-none-match返回304状态码
http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match

[MITM]
hostname = %APPEND% spclient.wg.spotify.com, *spclient.spotify.com

[Script]
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/djc666888/xiaowangzi/refs/heads/main/js/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://github.com/djc666888/xiaowangzi/blob/main/js/spotify-proto.js,script-update-interval=0
